INSERT INTO beta.continent (beta.continent.continent_name)
VALUES ('Europe', 'Asia', 'Africa', 'North America', 'South America', 'Oceania');

INSERT INTO beta.country (country_name, continent_id)
VALUES 
    ('United States', (SELECT continent_id FROM beta.continent WHERE continent_name = 'North America')),
    ('Nigeria', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Brazil', (SELECT continent_id FROM beta.continent WHERE continent_name = 'South America')),
    ('El Salvador', (SELECT continent_id FROM beta.continent WHERE continent_name = 'North America')),
    ('India', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Asia')),
    ('Canada', (SELECT continent_id FROM beta.continent WHERE continent_name = 'North America')),
    ('Ivory Coast', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Germany', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Croatia', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Tunisia', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Indonesia', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Asia')),
    ('Botswana', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Spain', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Japan', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Asia')),
    ('Sudan', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Algeria', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Ukraine', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Libya', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('China', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Asia')),
    ('Chile', (SELECT continent_id FROM beta.continent WHERE continent_name = 'South America')),
    ('Tanzania', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('France', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Bulgaria', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Mexico', (SELECT continent_id FROM beta.continent WHERE continent_name = 'North America')),
    ('Malawi', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Africa')),
    ('Italy', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Europe')),
    ('Philippines', (SELECT continent_id FROM beta.continent WHERE continent_name = 'Asia'));

INSERT INTO beta.city (city_name, country_id)
VALUES
    ('Los Angeles', (SELECT country_id FROM beta.country WHERE country_name = 'United States')),
    ('Lagos', (SELECT country_id FROM beta.country WHERE country_name = 'Nigeria')),
    ('Sao Paulo', (SELECT country_id FROM beta.country WHERE country_name = 'Brazil')),
    ('El Salvador', (SELECT country_id FROM beta.country WHERE country_name = 'El Salvador')),
    ('Kolkata', (SELECT country_id FROM beta.country WHERE country_name = 'India')),
    ('Toronto', (SELECT country_id FROM beta.country WHERE country_name = 'Canada')),
    ('Abidjan', (SELECT country_id FROM beta.country WHERE country_name = 'Ivory Coast')),
    ('Berlin', (SELECT country_id FROM beta.country WHERE country_name = 'Germany')),
    ('Zagreb', (SELECT country_id FROM beta.country WHERE country_name = 'Croatia')),
    ('Honolulu', (SELECT country_id FROM beta.country WHERE country_name = 'United States')),
    ('Chicago', (SELECT country_id FROM beta.country WHERE country_name = 'United States')),
    ('New York', (SELECT country_id FROM beta.country WHERE country_name = 'United States')),
    ('Tunis', (SELECT country_id FROM beta.country WHERE country_name = 'Tunisia')),
    ('Jakarta', (SELECT country_id FROM beta.country WHERE country_name = 'Indonesia')),
    ('Gaborone', (SELECT country_id FROM beta.country WHERE country_name = 'Botswana')),
    ('Madrid', (SELECT country_id FROM beta.country WHERE country_name = 'Spain')),
    ('Tokyo', (SELECT country_id FROM beta.country WHERE country_name = 'Japan')),
    ('Khartoum', (SELECT country_id FROM beta.country WHERE country_name = 'Sudan')),
    ('Algiers', (SELECT country_id FROM beta.country WHERE country_name = 'Algeria')),
    ('Kiev', (SELECT country_id FROM beta.country WHERE country_name = 'Ukraine')),
    ('Tripoli', (SELECT country_id FROM beta.country WHERE country_name = 'Libya')),
    ('Shanghai', (SELECT country_id FROM beta.country WHERE country_name = 'China')),
    ('Santiago', (SELECT country_id FROM beta.country WHERE country_name = 'Chile')),
    ('Dar es Salaam', (SELECT country_id FROM beta.country WHERE country_name = 'Tanzania')),
    ('Paris', (SELECT country_id FROM beta.country WHERE country_name = 'France')),
    ('Sofia', (SELECT country_id FROM beta.country WHERE country_name = 'Bulgaria')),
    ('Mexico City', (SELECT country_id FROM beta.country WHERE country_name = 'Mexico')),
    ('Blantyre', (SELECT country_id FROM beta.country WHERE country_name = 'Malawi')),
    ('Rome', (SELECT country_id FROM beta.country WHERE country_name = 'Italy')),
    ('Manila', (SELECT country_id FROM beta.country WHERE country_name = 'Philippines'));


INSERT INTO beta.town (town_name, city_id)
VALUES 
    ('South Whittier', (SELECT city_id FROM beta.city WHERE city_name = 'Los Angeles')),
    ('Efon-Alaaye', (SELECT city_id FROM beta.city WHERE city_name = 'Lagos')),
    ('Resplendor', (SELECT city_id FROM beta.city WHERE city_name = 'Sao Paulo')),
    ('Ilopango', (SELECT city_id FROM beta.city WHERE city_name = 'El Salvador')),
    ('Jashpurnagar', (SELECT city_id FROM beta.city WHERE city_name = 'Kolkata')),
    ('Markham', (SELECT city_id FROM beta.city WHERE city_name = 'Toronto')),
    ('Bonoua', (SELECT city_id FROM beta.city WHERE city_name = 'Abidjan')),
    ('Weimar', (SELECT city_id FROM beta.city WHERE city_name = 'Berlin')),
    ('Kahului', (SELECT city_id FROM beta.city WHERE city_name = 'Zagreb')),
    ('Longview', (SELECT city_id FROM beta.city WHERE city_name = 'Honolulu')),
    ('Bensheim', (SELECT city_id FROM beta.city WHERE city_name = 'Chicago')),
    ('Gainesville', (SELECT city_id FROM beta.city WHERE city_name = 'New York')),
    ('Yonkers', (SELECT city_id FROM beta.city WHERE city_name = 'Tunis')),
    ('Wangon', (SELECT city_id FROM beta.city WHERE city_name = 'Jakarta')),
    ('Tonota', (SELECT city_id FROM beta.city WHERE city_name = 'Gaborone')),
    ('Reus', (SELECT city_id FROM beta.city WHERE city_name = 'Madrid')),
    ('Carlos Barbosa', (SELECT city_id FROM beta.city WHERE city_name = 'Tokyo')),
    ('Friedberg', (SELECT city_id FROM beta.city WHERE city_name = 'Khartoum')),
    ('Charlottenburg-Nord', (SELECT city_id FROM beta.city WHERE city_name = 'Algiers')),
    ('Motomachi', (SELECT city_id FROM beta.city WHERE city_name = 'Kiev')),
    ('Ar Ruseris', (SELECT city_id FROM beta.city WHERE city_name = 'Tripoli')),
    ('El Achir', (SELECT city_id FROM beta.city WHERE city_name = 'Shanghai')),
    ('Hlukhiv', (SELECT city_id FROM beta.city WHERE city_name = 'Santiago')),
    ('Brunswick', (SELECT city_id FROM beta.city WHERE city_name = 'Dar es Salaam')),
    ('Ueno-ebisumachi', (SELECT city_id FROM beta.city WHERE city_name = 'Paris')),
    ('Ajdabiya', (SELECT city_id FROM beta.city WHERE city_name = 'Sofia')),
    ('Licheng', (SELECT city_id FROM beta.city WHERE city_name = 'Mexico City')),
    ('Gifhorn', (SELECT city_id FROM beta.city WHERE city_name = 'Blantyre')),
    ('Bachhraon', (SELECT city_id FROM beta.city WHERE city_name = 'Rome')),
    ('La Ligua', (SELECT city_id FROM beta.city WHERE city_name = 'Manila')),
    ('Dublin', (SELECT city_id FROM beta.city WHERE city_name = 'Los Angeles')),
    ('Malaut', (SELECT city_id FROM beta.city WHERE city_name = 'Lagos')),
    ('Magomeni', (SELECT city_id FROM beta.city WHERE city_name = 'Sao Paulo')),
    ('Fujioka', (SELECT city_id FROM beta.city WHERE city_name = 'El Salvador')),
    ('Valence', (SELECT city_id FROM beta.city WHERE city_name = 'Kolkata')),
    ('Pujali', (SELECT city_id FROM beta.city WHERE city_name = 'Toronto')),
    ('Smolyan', (SELECT city_id FROM beta.city WHERE city_name = 'Abidjan')),
    ('Zacoalco de Torres', (SELECT city_id FROM beta.city WHERE city_name = 'Berlin')),
    ('Salima', (SELECT city_id FROM beta.city WHERE city_name = 'Zagreb')),
    ('Catania', (SELECT city_id FROM beta.city WHERE city_name = 'Honolulu')),
    ('Calauan', (SELECT city_id FROM beta.city WHERE city_name = 'Chicago')),
    ('Acayucan', (SELECT city_id FROM beta.city WHERE city_name = 'New York'));


INSERT INTO beta.plant (plant_id, plant_name, plant_scientific_name, town_id)
VALUES
    (1, 'Venus flytrap', 'Dionaea muscipula', (SELECT town_id FROM beta.town WHERE town_name = 'South Whittier')),
    (2, 'Corpse flower', 'Amorphophallus titanum', (SELECT town_id FROM beta.town WHERE town_name = 'Efon-Alaaye')),
    (3, 'Rafflesia arnoldii', 'Rafflesia arnoldii', (SELECT town_id FROM beta.town WHERE town_name = 'Resplendor')),
    (4, 'Black bat flower', 'Tacca palmata', (SELECT town_id FROM beta.town WHERE town_name = 'Ilopango')),
    (5, 'Pitcher plant', 'Sarracenia catesbaei', (SELECT town_id FROM beta.town WHERE town_name = 'Jashpurnagar')),
    (6, 'Wollemi pine', 'Wollemia nobilis', (SELECT town_id FROM beta.town WHERE town_name = 'Markham')),
    (8, 'Bird of paradise', 'Heliconia schiedeana \'Fire and Ice\'', (SELECT town_id FROM beta.town WHERE town_name = 'Bonoua')),
    (9, 'Cactus', 'Pereskia grandifolia', (SELECT town_id FROM beta.town WHERE town_name = 'Weimar')),
    (10, 'Dragon tree', 'Dracaena draco', (SELECT town_id FROM beta.town WHERE town_name = 'Split')),
    (11, 'Asclepias curassavica', 'Asclepias curassavica', (SELECT town_id FROM beta.town WHERE town_name = 'Kahului')),
    (12, 'Angel’s trumpet', 'Brugmansia x candida', (SELECT town_id FROM beta.town WHERE town_name = 'Longview')),
    (13, 'Canna lily', 'Canna indica', (SELECT town_id FROM beta.town WHERE town_name = 'Bensheim')),
    (14, 'Taro', 'Colocasia esculenta', (SELECT town_id FROM beta.town WHERE town_name = 'Gainesville')),
    (16, 'Euphorbia', 'Euphorbia cotinifolia', (SELECT town_id FROM beta.town WHERE town_name = 'Yonkers')),
    (17, 'Sweet potato', 'Ipomoea batatas', (SELECT town_id FROM beta.town WHERE town_name = 'Wangon')),
    (19, 'Banana plant', 'Musa basjoo', (SELECT town_id FROM beta.town WHERE town_name = 'Tonota')),
    (20, 'Salvia', 'Salvia splendens', (SELECT town_id FROM beta.town WHERE town_name = 'Reus')),
    (21, 'Anthurium', 'Anthurium andraeanum', (SELECT town_id FROM beta.town WHERE town_name = 'Carlos Barbosa')),
    (22, 'Bird of paradise', 'Heliconia schiedeana \'Fire and Ice\'', (SELECT town_id FROM beta.town WHERE town_name = 'Friedberg')),
    (23, 'Cordyline', 'Cordyline fruticosa', (SELECT town_id FROM beta.town WHERE town_name = 'Charlottenburg-Nord')),
    (24, 'Ficus', 'Ficus carica', (SELECT town_id FROM beta.town WHERE town_name = 'Motomachi')),
    (25, 'Palm trees', 'Arecaceae', (SELECT town_id FROM beta.town WHERE town_name = 'Ar Ruseris')),
    (26, 'Dieffenbachia', 'Dieffenbachia seguine', (SELECT town_id FROM beta.town WHERE town_name = 'El Achir')),
    (27, 'Spathiphyllum', 'Spathiphyllum', (SELECT town_id FROM beta.town WHERE town_name = 'Hlukhiv')),
    (28, 'Croton', 'Codiaeum variegatum', (SELECT town_id FROM beta.town WHERE town_name = 'Brunswick')),
    (29, 'Aloe vera', 'Aloe vera', (SELECT town_id FROM beta.town WHERE town_name = 'Ueno-ebisumachi')),
    (30, 'Ficus elastica', 'Ficus elastica', (SELECT town_id FROM beta.town WHERE town_name = 'Ajdabiya')),
    (31, 'Sansevieria', 'Sansevieria trifasciata', (SELECT town_id FROM beta.town WHERE town_name = 'Licheng')),
    (32, 'Philodendron', 'Philodendron hederaceum', (SELECT town_id FROM beta.town WHERE town_name = 'Gifhorn')),
    (33, 'Schefflera', 'Schefflera arboricola', (SELECT town_id FROM beta.town WHERE town_name = 'Bachhraon')),
    (34, 'Aglaonema', 'Aglaonema commutatum', (SELECT town_id FROM beta.town WHERE town_name = 'Reus')),
    (35, 'Monstera', 'Monstera deliciosa', (SELECT town_id FROM beta.town WHERE town_name = 'La Ligua')),
    (36, 'Tacca', 'Tacca integrifolia', (SELECT town_id FROM beta.town WHERE town_name = 'Dublin')),
    (37, 'Psychopsis', 'Psychopsis papilio', (SELECT town_id FROM beta.town WHERE town_name = 'Malaut')),
    (38, 'Saintpaulia', 'Saintpaulia ionantha', (SELECT town_id FROM beta.town WHERE town_name = 'Magomeni')),
    (39, 'Gaillardia', 'Gaillardia aestivalis', (SELECT town_id FROM beta.town WHERE town_name = 'Fujioka')),
    (40, 'Amaryllis', 'Hippeastrum', (SELECT town_id FROM beta.town WHERE town_name = 'Valence')),
    (41, 'Caladium', 'Caladium bicolor', (SELECT town_id FROM beta.town WHERE town_name = 'Pujali')),
    (42, 'Chlorophytum', 'Chlorophytum comosum', (SELECT town_id FROM beta.town WHERE town_name = 'Smolyan')),
    (44, 'Araucaria', 'Araucaria heterophylla', (SELECT town_id FROM beta.town WHERE town_name = 'Zacoalco de Torres')),
    (45, 'Begonia', 'Begonia \'Art Hodes\'', (SELECT town_id FROM beta.town WHERE town_name = 'South Whittier')),
    (46, 'Medinilla', 'Medinilla magnifica', (SELECT town_id FROM beta.town WHERE town_name = 'Salima')),
    (47, 'Calliandra', 'Calliandra haematocephala', (SELECT town_id FROM beta.town WHERE town_name = 'Catania')),
    (48, 'Zamioculcas', 'Zamioculcas zamiifolia', (SELECT town_id FROM beta.town WHERE town_name = 'Calauan')),
    (49, 'Crassula', 'Crassula ovata', (SELECT town_id FROM beta.town WHERE town_name = 'Acayucan')),
    (50, 'Epipremnum', 'Epipremnum aureum', (SELECT town_id FROM beta.town WHERE town_name = 'Resplendor'));


INSERT INTO beta.botanist (first_name, last_name, phone, email)
VALUES  
    ('Gertrude', 'Jekyll', '001-481-273-3691x127', 'gertrude.jekyll@lnhm.co.uk'),  
    ('Carl', 'Linnaeus', '(146)994-1635x35992', 'carl.linnaeus@lnhm.co.uk'),  
    ('Eliza', 'Andrews', '(846)669-6651x75948', 'eliza.andrews@lnhm.co.uk'); 