name: Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: $ {{ runner.os }}-pip-$
              {{ hashFiles('**/requirements.txt') }}
          restore-keys: |
                    $ 
                    {{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run pipeline tests
        run: |
          cd pipeline
          pip install -r requirements.txt
          pytest . --maxfail=1


      - name: Run dashboard tests
        run: |
          cd dashboard
          pip install -r requirements.txt
          pytest . --maxfail=1
        

      - name: Run archive lambda tests
        run: |
          cd archive_lambda
          pip install -r requirements.txt
          pytest . --maxfail=1
      
      
      - name: Run sns trigger lambda tests
        run: |
          cd sns_trigger_lambda
          pip install -r requirements.txt
          pytest . --maxfail=1
